export const REQUEST_SHOPS = 'REQUEST_SHOPS';
export const RECEIVE_SHOPS = 'RECEIVE_SHOPS';
export const REQUEST_SHOP_DETAIL = 'REQUEST_SHOP_DETAIL';
export const RECEIVE_SHOP_DETAIL = 'RECEIVE_SHOP_DETAIL';
export const INIT_SHOP_DETAIL = 'INIT_SHOP_DETAIL';

